### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jcjohnny** [jcjohnny/rvngrplyr#1]
Please review my project proposal. 

@jasonseminara 
@zhenpanda 
@amcooper 
@WilliamfShaw

**Comment by jasonseminara** [comment]
This looks like a great idea for the data viz, but I'm not clear how the user interaction works. Please more clearly explain the user stories.

**Comment by jcjohnny** [comment]
updated readme and added user stories to trello please take a look.
@jasonseminara  @zhenpanda 

-edit- I welcome any and all suggestions

**Comment by jasonseminara** [comment]
approved
